LOAD DATA INFILE '/Users/jamie/source/betes2/d3js_app/db/carelink_data.csv'
INTO TABLE insight_entries_carelink
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(DeviceIndex,
  @NotUsed,
  @NotUsed,
  @ConvertedResultDate,
  NewDeviceTime,
  bsLevel,
  LinkedBGMeterID,
  TempBasalAmount,
  TempBasalType,
  TempBasalDuration,
  BolusType,
  BolusVolumeSelected,
  BolusVolumeDelivered,
  ProgrammedBolusDuration,
  PrimeType,
  PrimeVolumeDelivered,
  Suspend,
  Rewind,
  BWZEstimate,
  BWZTargetHighBG,
  BWZTargetLowBG,
  BWZCarbRatio,
  BWZInsulinSensitivity,
  BWZCarbInput,
  BWZBGInput,
  BWZCorrectionEstimate,
  BWZFoodEstimate,
  BWZActiveInsulin,
  Alarm,
  SensorCalibrationBG,
  SensorGlucose,
  ISIGValue,
  DailyInsulinTotal,
  RawType,
  @RawValuesList,
  RawID,
  RawUploadID,
  RawSeqNum,
  RawDeviceType)
SET resultDate = STR_TO_DATE(@ConvertedResultDate, '%m/%d/%Y %H:%i'), RawValues = REPLACE(@RawValuesList, ',', ':'), userId = 101 , updated_at = NOW();